<?php

/**
 * @file
 * Enables permitted roles to upload files for insertion into configured nodes.
 */

define('FILEPICKER_FILES_DIR', 'filepicker');
define('FILEPICKER_ADMIN_PATH', 'admin/config/media/filepicker');
define('FILEPICKER_PATH', drupal_get_path('module', 'filepicker'));
define('FILEPICKER_FILE_SCHEME', file_default_scheme() . '://');
// Minimum PHP version for extension
define('FILEPICKER_UPLOAD_STATUS_MIN_PHP', '5.2.1');
define('FILEPICKER_UPLOAD_ID', 'UPLOAD_IDENTIFIER');


/**
 * Implements hook_help().
 */
function filepicker_help($path, $arg) {
  switch ($path) {
    case 'admin/help#filepicker':
      $output = '<p>' . t('Adds an advanced file upload form under the node body part.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_permission().
 */
function filepicker_permission() {

  return array(
    'administer filepicker' => array(
      'title' => t('Administer Filepicker'),
      'description' => t('Access the Filepicker administration pages.'),
      ),
    'use filepicker' => array(
      'title' => t('Use Filepicker'),
      'description' => t('Allow roles to use Filepicker.'),
      ),
    'access own filepicker' => array(
      'title' => t('Access own Filepicker'),
      'description' => t('Allow users to have My Filepicker in My account.'),
      ),
    'use public filepicker' => array(
      'title' => t('Use public filepicker'),
      'description' => t('Allow the use of public groups.'),
      ),
    'create public filepicker groups' => array(
      'title' => t('Create public groups'),
      'description' => t('Allow the creation of public groups in filepicker.'),
      ),
  );
}

/**
 * Implements hook_init().
 */
function filepicker_init() {
  global $user;
  if ($user->uid > 0) {
    module_load_include('inc', 'filepicker', 'filepicker.functions');
#    module_load_include('inc', 'filepicker', 'filepicker.theme');
    module_load_include('inc', 'filepicker', 'filepicker.form-elements');
  }
}

/**
 * Implements hook_menu().
 */
function filepicker_menu() {

  $items = array();
  $items['filepicker'] = array(
    'title'            => 'File picker',
    'page callback'    => 'filepicker_box',
    'access callback'  => 'filepicker_access_use',
    'type'             => MENU_CALLBACK,
    'file'             => 'filepicker.upload.inc',
    'theme callback'   => 'filepicker_access_theme',
  );
  $items['filepicker/upload'] = array(
    'title'            => 'Upload',
    'access callback'  => 'filepicker_access_use',
    'type'             => MENU_DEFAULT_LOCAL_TASK,
    'weight'           => 0,
  );
  $items['filepicker/list'] = array(
    'title'            => 'List',
    'page callback'    => 'filepicker_box',
    'access callback'  => 'filepicker_access_use',
    'type'             => MENU_LOCAL_TASK,
    'weight'           => 2,
  );
  $items['filepicker/list_public'] = array(
    'title'            => 'List Public',
    'page callback'    => 'filepicker_box',
    'access callback'  => 'filepicker_access_use_public',
    'type'             => MENU_LOCAL_TASK,
    'weight'           => 3
  );
  $items['filepicker/groups'] = array(
    'title'            => 'Groups',
    'page callback'    => 'filepicker_box',
    'access callback'  => 'filepicker_access_use_group',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.group.inc',
    'weight'           => 4
  );
  $items['filepicker/list/%filepicker_id'] = array(
    'title'            => 'List',
    'page callback'    => 'filepicker_box',
    'access callback'  => 'filepicker_access_use',
    'type'             => MENU_LOCAL_TASK,
    'weight'           => 2
  );
  $items['filepicker/edit/%filepicker_id'] = array(
    'title'            => 'Edit file',
    'page callback'    => 'filepicker_box',
    'access callback'  => 'filepicker_access_use',
    'type'             => MENU_CALLBACK,
    'file'             => 'filepicker.edit.inc'
  );
  // uploadprogress callback
  $items['filepicker/progress'] = array(
    'page callback' => 'filepicker_uploadprogress_callback',
    'access arguments' => array(TRUE),
    'type' => MENU_CALLBACK,
  );
  // multitask
  $items['filepicker/multitask/%/%/%'] = array(
    'title' => 'Bulk Operations',
    'page callback' => 'filepicker_box',
    'access callback'  => 'filepicker_access_use',
    'type' => MENU_CALLBACK,
  );
  // admin settings
  $items[FILEPICKER_ADMIN_PATH] = array(
    'title'            => 'Filepicker',
    'description'      => 'Filepicker settings and administration.',
    'page callback'    => 'filepicker_settings_page',
    'access callback'  => 'filepicker_access_admin',
    'type'             => MENU_NORMAL_ITEM,
    'file'             => 'filepicker.admin.inc',
    'weight'           => 0
  );
  $items[FILEPICKER_ADMIN_PATH . '/general'] = array(
    'title'            => 'General',
    'description'      => 'Filepicker settings.',
    'page callback'    => 'filepicker_settings_page',
    'access callback'  => 'filepicker_access_admin',
    'type'             => MENU_DEFAULT_LOCAL_TASK,
    'file'             => 'filepicker.admin.inc',
    'weight'           => -10
  );
  // admin groups and files
  $items[FILEPICKER_ADMIN_PATH . '/groups'] = array(
    'title'            => 'Groups',
    'description'      => 'Show user groups.',
    'access callback'  => 'filepicker_access_admin_group',
    'page callback'    => 'filepicker_admin_groups',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.admin.inc',
    'weight'           => -8
  );
  $items[FILEPICKER_ADMIN_PATH . '/groups/users'] = array(
    'title'            => 'Users',
    'description'      => 'Show user groups.',
    'access callback'  => 'filepicker_access_admin_group',
    'page callback'    => 'filepicker_admin_groups',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.admin.inc',
    'weight'           => -10
  );
  $items[FILEPICKER_ADMIN_PATH . '/groups/stats'] = array(
    'title'            => 'Stats',
    'description'      => 'Show user group stats.',
    'access callback'  => 'filepicker_access_admin_group',
    'page callback'    => 'filepicker_admin_groups',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.admin.inc',
    'weight'           => -8
  );
  $items[FILEPICKER_ADMIN_PATH . '/groups/user/%filepicker_id'] = array(
    'title'            => 'Groups',
    'description'      => 'Show user groups.',
    'access callback'  => 'filepicker_access_admin_group',
    'page callback'    => 'filepicker_admin_groups',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.admin.inc',
    'weight'           => -7
  );
  $items[FILEPICKER_ADMIN_PATH . '/groups/user/%filepicker_id/stats'] = array(
    'title'            => 'Stats',
    'description'      => 'Show user stats.',
    'access callback'  => 'filepicker_access_admin_group',
    'page callback'    => 'filepicker_admin_groups',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.admin.inc',
    'weight'           => -8
  );
  $items[FILEPICKER_ADMIN_PATH . '/groups/autocomplete'] = array(
    'access callback'  => 'filepicker_access_admin_group',
    'page callback'    => 'filepicker_group_search_autocomplete',
    'type'             => MENU_CALLBACK,
    'file'             => 'filepicker.admin.inc'
  );
  $items[FILEPICKER_ADMIN_PATH . '/files/stats'] = array(
    'title'            => 'Stats All',
    'description'      => 'Show user statistics.',
    'access callback'  => 'filepicker_access_admin_group',
    'page callback'    => 'filepicker_admin_files',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.admin.inc',
    'weight'           => -7
  );
  // admin filepicker
  $items[FILEPICKER_ADMIN_PATH . '/files'] = array(
    'title'            => 'Files',
    'description'      => 'Show user files.',
    'access callback'  => 'filepicker_access_admin',
    'page callback'    => 'filepicker_admin_files',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.admin.inc',
    'weight'           => -9
  );
  $items[FILEPICKER_ADMIN_PATH . '/files/list_all'] = array(
    'title'            => 'List All',
    'description'      => 'List user files.',
    'access callback'  => 'filepicker_access_admin',
    'page callback'    => 'filepicker_admin_files',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.admin.inc',
    'weight'           => -8
  );
  $items[FILEPICKER_ADMIN_PATH . '/files/users'] = array(
    'title'            => 'Users',
    'description'      => 'List users.',
    'access callback'  => 'filepicker_access_admin',
    'page callback'    => 'filepicker_admin_files',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.admin.inc',
    'weight'           => -10
  );
  $items[FILEPICKER_ADMIN_PATH . '/files/user/%filepicker_id/list'] = array(
    'title'            => 'List',
    'description'      => 'List user files.',
    'access callback'  => 'filepicker_access_admin',
    'page callback'    => 'filepicker_admin_files',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.admin.inc',
    'weight'           => -3
  );
  $items[FILEPICKER_ADMIN_PATH . '/files/user/%filepicker_id/upload'] = array(
    'title'            => 'Upload',
    'description'      => 'Upload user files.',
    'access callback'  => 'filepicker_access_admin',
    'page callback'    => 'filepicker_admin_files',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.admin.inc',
    'weight'           => -6
  );
  $items[FILEPICKER_ADMIN_PATH . '/files/user/%filepicker_id/stats'] = array(
    'title'            => 'Stats',
    'description'      => 'Show user stats.',
    'access callback'  => 'filepicker_access_admin_group',
    'page callback'    => 'filepicker_admin_files',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.admin.inc',
    'weight'           => -2
  );
  $items[FILEPICKER_ADMIN_PATH . '/files/user/%filepicker_id/groups'] = array(
    'title'            => 'Groups',
    'description'      => 'List user groups.',
    'access callback'  => 'filepicker_access_admin_group',
    'page callback'    => 'filepicker_admin_files',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.admin.inc',
    'weight'           => -1
  );
  $items[FILEPICKER_ADMIN_PATH . '/files/autocomplete'] = array(
    'access callback'  => 'filepicker_access_admin',
    'page callback'    => 'filepicker_user_autocomplete',
    'type'             => MENU_CALLBACK,
    'file'             => 'filepicker.admin.inc'
  );
  // Import
  $items[FILEPICKER_ADMIN_PATH . '/import'] = array(
    'title'            => 'Import',
    'description'      => 'Manage bulk imports.',
    'page callback'    => 'filepicker_admin_import',
    'access callback'  => 'filepicker_access_import',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.admin.inc',
    'weight'           => -8
  );
  $items[FILEPICKER_ADMIN_PATH . '/import/autocomplete'] = array(
    'access callback'  => 'filepicker_access_import',
    'page callback'    => 'filepicker_user_autocomplete',
    'type'             => MENU_CALLBACK,
    'file'             => 'filepicker.admin.inc'
  );
  $items[FILEPICKER_ADMIN_PATH . '/import/user/%filepicker_id'] = array(
    'title'            => 'Import',
    'description'      => 'Import files.',
    'access callback'  => 'filepicker_access_import',
    'page callback'    => 'filepicker_admin_import',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.admin.inc',
    'weight'           => -3
  );
  // multitask
  $items[FILEPICKER_ADMIN_PATH . '/multitask/%/%/%'] = array(
    'title' => 'Bulk Operations',
    'page callback' => 'filepicker_multitask',
    'page arguments'   => array(5, 6, 7),
    'access callback'  => 'filepicker_access_admin',
    'type' => MENU_CALLBACK,
  );
  // orphans
  $items[FILEPICKER_ADMIN_PATH . '/orphans'] = array(
    'title'            => 'Orphaned files',
    'description'      => 'Manage orphaned files.',
    'page callback'    => 'filepicker_admin_orphans',
    'access callback'  => 'filepicker_access_admin',
    'type'             => MENU_CALLBACK,
    'file'             => 'filepicker.admin.inc',
  );
  $items[FILEPICKER_ADMIN_PATH . '/orphans/autocomplete'] = array(
    'access callback'  => 'filepicker_access_admin',
    'page callback'    => 'filepicker_user_autocomplete',
    'type'             => MENU_CALLBACK,
    'file'             => 'filepicker.admin.inc'
  );
  // My filepicker
  $items['user/%filepicker_uid/filepicker'] = array(
    'title'            => 'My filepicker',
    'description'      => 'Manage your filepicker files.',
    'page callback'    => 'filepicker_user_page',
    'page arguments'   => array(1),
    'access callback'  => 'filepicker_access_user_pages',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.user.inc',
    'weight'           => 0
  );
  $items['user/%filepicker_uid/filepicker/upload'] = array(
    'title'            => 'Upload',
    'description'      => 'Upload files.',
    'page callback'    => 'filepicker_user_page',
    'page arguments'   => array(1, 3),
    'access callback'  => 'filepicker_access_user_pages',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.user.inc',
    'weight'           => -9
  );
  $items['user/%filepicker_uid/filepicker/files/list'] = array(
    'title'            => 'List',
    'description'      => 'List your filepicker files.',
    'page callback'    => 'filepicker_user_page',
    'page arguments'   => array(1, 3, 4, 5),
    'access callback'  => 'filepicker_access_user_pages',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.user.inc',
    'weight'           => -6
  );
  // groups
  $items['user/%filepicker_uid/filepicker/files/list_public'] = array(
    'title'            => 'List Public',
    'description'      => 'List public filepicker files.',
    'page callback'    => 'filepicker_user_page',
    'page arguments'   => array(1, 3, 4, 5),
    'access callback'  => 'filepicker_access_user_public',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.user.inc',
    'weight'           => -5
  );
  $items['user/%filepicker_uid/filepicker/groups/list'] = array(
    'title'            => 'Groups',
    'description'      => 'Manage your filepicker groups.',
    'page callback'    => 'filepicker_user_page',
    'page arguments'   => array(1, 3, 4, 5),
    'access callback'  => 'filepicker_access_user_groups',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.user.inc',
    'weight'           => -4
  );
  $items['user/%filepicker_uid/filepicker/stats'] = array(
    'title'            => 'Stats',
    'description'      => 'View your filepicker statistics.',
    'page callback'    => 'filepicker_user_page',
    'page arguments'   => array(1, 3),
    'access callback'  => 'filepicker_access_user_groups',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.user.inc',
    'weight'           => -3
  );
  $items['user/%filepicker_uid/filepicker/config'] = array(
    'title'            => 'Config',
    'description'      => 'Administer user configuration.',
    'page callback'    => 'filepicker_user_page',
    'page arguments'   => array(1, 3),
    'access callback'  => 'filepicker_access_user_config',
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'filepicker.user.inc',
    'weight'           => -2
  );
  // multitask
  $items['user/%filepicker_uid/filepicker/multitask/%/%/%'] = array(
    'title' => 'Bulk Operations',
    'page callback' => 'filepicker_multitask',
    'page arguments'   => array(4, 5, 6),
    'access callback'  => 'filepicker_access_user_pages',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * menu placeholder functions
 */
function filepicker_id_load($arg) {
  return (is_numeric($arg) ? $arg : FALSE);
}

function filepicker_uid_load($arg) {
  global $user;
  return ((is_numeric($arg) && $user->uid == $arg) ? $arg : FALSE);
}

/**
 * Menu access callback functions.
 */
function filepicker_access_import() {
  if (filepicker_variable_get('filepicker_import_enabled', 0) && user_access('administer filepicker')) {
    return TRUE;
  }
  return FALSE;
}

function filepicker_access_user_pages() {
  if (filepicker_variable_get('filepicker_account_enabled', 1) && user_access('access own filepicker') ) {
    return TRUE;
  }
  return FALSE;
}

function filepicker_access_user_config() {
  if (filepicker_variable_get('filepicker_account_enabled', 1)
      && user_access('access own filepicker')
      && filepicker_variable_get('filepicker_user_config_enable', 1)
  ) {
    return TRUE;
  }
  return FALSE;
}

function filepicker_access_user_groups() {
  if (filepicker_variable_get('filepicker_account_enabled', 1)
      && user_access('access own filepicker')
      && filepicker_variable_get('filepicker_groups_enabled', 1)
    ) {
    return TRUE;
  }
  return FALSE;
}

function filepicker_access_user_public() {
  if (filepicker_variable_get('filepicker_account_enabled', 1)
      && user_access('access own filepicker')
      && filepicker_variable_get('filepicker_groups_enabled', 1)
      && user_access('use public filepicker')
      && filepicker_variable_get('filepicker_public_enabled', 1)
    ) {
    return TRUE;
  }
  return FALSE;
}

function filepicker_access_admin_group() {
  if (filepicker_variable_get('filepicker_groups_enabled', 1)
      && user_access('administer filepicker')
    ) {
    return TRUE;
  }
  return FALSE;
}

function filepicker_access_admin() {
  if (user_access('administer filepicker')) {
    return TRUE;
  }
  return FALSE;
}

function filepicker_access_use() {
  if (user_access('use filepicker')) {
    return TRUE;
  }
  return FALSE;
}

function filepicker_access_use_public() {
  if (user_access('use public filepicker') && filepicker_variable_get('filepicker_public_enabled', 1)) {
    return TRUE;
  }
  return FALSE;
}

function filepicker_access_use_group() {
  if (user_access('use filepicker') && filepicker_variable_get('filepicker_groups_enabled', 1)) {
    return TRUE;
  }
  return FALSE;
}

function filepicker_access_theme() {

  if (filepicker_variable_get('filepicker_use_admin_theme', 0) && variable_get('node_admin_theme', 0)) {
    return variable_get('admin_theme');
  }
  return FALSE;
}

/**
 * Implements hook_form_alter().
 */
function filepicker_form_alter(&$form, &$form_state, $form_id) {

  global $user;
  if (user_access('use filepicker')) {
    $weight = 1;
    $insert_type = '';
    // is this a node edit form
    if (!empty($form['#node_edit_form']) && preg_match('/node_form$/i', $form_id)) {
      // get the object
      $node = $form['#node'];
      $node_types = node_type_get_names();

      // zxx issue. zxx stands for 'no language' but it might change....
      // we pick this up in theme_filepicker which hands it to filepicker_iframe.js
      $node_lang = filepicker_variable_get('filepicker_node_lang', '');
      $node_language = (isset($node->language) ? $node->language : 'und');
      if (! $node_lang || $node_lang != $node_language) {
        filepicker_variable_set('filepicker_node_lang', $node_language);
        // don't know what the number is for, so hardwire it for now
        filepicker_variable_set('filepicker_node_pos', 0);
      }

      $node_type = in_array($node->type, filepicker_variable_get('filepicker_node_types_enabled', array_keys($node_types)), TRUE);
      if ($node_type) {
        $insert_type = 'node';
      }
    }
    elseif (module_exists('comment') && filepicker_variable_get('filepicker_comment_enabled', 0) && preg_match('/comment.*_form$/i', $form_id) ) {
      $insert_type = 'comment';
    }
    elseif (( $form_id == 'block_add_block_form' || $form_id == 'block_admin_configure' ) && filepicker_variable_get('filepicker_blocks_enabled', 0)) {
      $insert_type = 'block';
    }

    $width = filepicker_variable_get('filepicker_advanced_iframe_width', filepicker_variable_get('filepicker_advanced_iframe_width', "100%"), $user->uid);
    if (! preg_match("/%$/", $width)) {
      $width .= 'px';
    }
    $height = filepicker_variable_get('filepicker_advanced_iframe_height', filepicker_variable_get('filepicker_advanced_iframe_height', 500), $user->uid);
    $border = filepicker_variable_get('filepicker_advanced_iframe_border', filepicker_variable_get('filepicker_advanced_iframe_border', "0"), $user->uid);

    if (filepicker_get_colorbox_perms()) {
      $iurl = l(t('Run filepicker'), 'filepicker', array(
        'query' => array('width' => $width, 'height' => $height, 'iframe' => 'true'),
        'attributes' => array('class' => array('colorbox-load'))
      ));
    }
    else {
      $iurl = '<iframe id="filepicker" style="width: ' . $width . '; height: ' . $height . 'px; border: ' . $border . ';" src="' . url('filepicker') . '">Filepicker requires iframe support.</iframe>';
    }

    $fselement = array(
      '#type' => 'fieldset',
      '#title' => t('File picker'),
      '#collapsible' => 1,
      '#collapsed' => filepicker_variable_get('filepicker_advanced_collapsed', filepicker_variable_get('filepicker_advanced_collapsed', 0), $user->uid),
      '#weight' => $weight,
    );
    $mkelement = array(
      '#type' => 'markup',
      '#markup' => '<div id="filep_tb">' . $iurl . '</div>',
    );

    if ($insert_type == 'node') {
      $form['body']['filepicker_file_upload'] = $fselement;
      $form['body']['filepicker_file_upload']['mpframe'] = $mkelement;
      $form['body']['#prefix'] = '<a name="body_hash"></a>' . (isset($form['body']['#prefix']) ? $form['body']['#prefix'] : '');
    }
    elseif ($insert_type == 'block') {
      $form['settings']['body_field']['filepicker_file_upload'] = $fselement;
      $form['settings']['body_field']['filepicker_file_upload']['mpframe'] =  $mkelement;
      $form['settings']['body_field']['#prefix'] = '<a name="body_hash"></a>' . (isset($form['settings']['body_field']['#prefix']) ? $form['settings']['body_field']['#prefix'] : '');
    }
    elseif ($insert_type == 'comment') {
      $form['comment']['filepicker_file_upload'] = $fselement;
      $form['comment']['filepicker_file_upload']['mpframe'] = $mkelement;
      $form['comment']['#prefix'] = '<a name="body_hash"></a>' . (isset($form['comment']['#prefix']) ? $form['comment']['#prefix'] : '');
    }
  }
}

/**
 * @param string $varname
 *   .
 * @param string $default
 *   .
 * @param int $uid
 *   .
 *
 * @return
 *   string.
 *
 */
function filepicker_variable_get($varname, $default = NULL, $uid = FALSE) {
  // db table filepicker_variables
  if (!$uid) {
    $uid = 0;
  }
  $query = db_select('filepicker_variables', 'v');
  $query->fields('v', array('value'));
  $query->condition('v.name', $varname);
  $query->condition('v.uid', $uid);
  $row = $query->execute()->fetchObject();

  return (isset($row->value) ? unserialize($row->value) : $default);
}

function filepicker_variable_set($varname, $value, $uid = FALSE) {
  // db table filepicker_variables
  if (!$uid) {
    $uid = 0;
  }
  if ($varname) {
    // from bootstrap
    db_merge('filepicker_variables')
      ->key(array('name' => $varname, 'uid' => $uid))
      ->fields(array('value' => serialize($value), 'uid' => $uid))
      ->execute();
  }
}

function filepicker_variable_del($varname, $uid = FALSE) {
  // db table filepicker_variables
  if (!$uid) {
    $uid = 0;
  }
  if ($varname) {
    db_delete('filepicker_variables')
      ->condition('name', $varname)
      ->condition('uid', $uid)
      ->execute();
  }
}

function filepicker_get_colorbox_perms() {
  global $user;
  if ((module_exists('colorbox')
    && filepicker_variable_get('filepicker_advanced_colorbox', 0, $user->uid)
    && filepicker_variable_get('filepicker_advanced_colorbox', 0 )
    && variable_get('colorbox_load', 0))
    ) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_file_download().
 */
function filepicker_file_download($filepath) {
  $filebasedir = filepicker_get_files_directory(TRUE);
  $file = $filebasedir . DIRECTORY_SEPARATOR . file_uri_target($filepath);
  if (file_exists($file) & is_file($file)) {
    // There is a file, and it's in our directory structure. So send it.
    $mimetype = file_get_mimetype($filepath);
    return array('Content-type:' . $mimetype);
  }
  else {
    $path_parts = explode('/', $filepath);
    if ($path_parts[0] == FILEPICKER_FILES_DIR) {
      // The file is allegedly in our directory, but doesn't exist.
      return -1;
    }
  }
  // Not our file; let someone else decide.
  return NULL;
}
/**
 * some common utilities
 */
function filepicker_get_path($url = FALSE, $userdir = FALSE, $scheme = FALSE) {
  global $base_url;

  $dirsep = !$url ? DIRECTORY_SEPARATOR : '/';

  if (! $url && ! $scheme) {
    $path = filepicker_get_files_directory() . $dirsep;
  }
  else {
    if (filepicker_variable_get('filepicker_use_full_url', 0)) {
      $path = $base_url;
    }
    else {
      $path = base_path();
      $path = preg_replace("/\/$/", "", $path);
    }

    if ($scheme) {
      $path = FILEPICKER_FILES_DIR . $dirsep;
    }
    else {
      $path .= $dirsep . file_stream_wrapper_get_instance_by_scheme(file_default_scheme())->getDirectoryPath() . $dirsep . FILEPICKER_FILES_DIR . $dirsep;
    }
  }

  if ($userdir) {
    $path .= filepicker_get_userpath($userdir, $dirsep);
  }

  return $path;
}

function filepicker_get_userpath($userdir, $dirsep = '/') {
  global $user;
  $path = '';
  $useruid = !is_array($userdir) ? $user->uid : $userdir['uid'];
  $path .= $useruid . $dirsep;
  return $path;
}

function filepicker_get_file_path($file, $public = FALSE) {
  $userdir = is_array($public) ? $public : TRUE;
  $filebasedir = filepicker_get_path(FALSE, $userdir);
  if (is_object($file)) {
    $file_name = $file->file_name;
  }
  else {
    $file_name = $file['file_name'];
  }
  $filepath = '';
  if (file_exists($filebasedir . $file_name)) {
    if (variable_get('filepicker_use_full_url', 0) || file_default_scheme() == 'private') {
      $filepath = file_create_url(FILEPICKER_FILE_SCHEME . FILEPICKER_FILES_DIR . '/' . filepicker_get_userpath($userdir) . $file_name);
    }
    else {
      $filepath = filepicker_get_path(TRUE, $userdir) . $file_name;
    }
  }

  return $filepath;
}

function filepicker_get_files_directory($system_only = FALSE) {
  $file_default_scheme = file_default_scheme();
  $drupal_path = file_stream_wrapper_get_instance_by_scheme($file_default_scheme)->getDirectoryPath();
  if ($file_default_scheme == 'private') {
    $drupaldir = $drupal_path;
  }
  else {
    $drupaldir = str_replace('/', DIRECTORY_SEPARATOR, getcwd()) . DIRECTORY_SEPARATOR . $drupal_path;

  }
  if ($system_only) {
    return $drupaldir;
  }
  $dir = $drupaldir . DIRECTORY_SEPARATOR . FILEPICKER_FILES_DIR;
  return $dir;
}

/**
 * @file
 * Theme functions for filepicker.
 */

/**
 * theme registry
 */
function filepicker_theme() {
  return array(
    'filepicker' => array(
      'variables' => array('content' => NULL),
      'template' => 'filepicker',
    ),

    'filepicker_iframe' => array(
      'variables' => array(
        'content' => NULL,
        'file'  => NULL,
        'public'  => NULL,
      ),
    ),
    'filepicker_list' => array(
      'variables' => array(
        'header' => array(),
        'rows' => array(),
        'max' => 50,
        'message' => "",
        'pref' => "",
        'suff' => "",
        'label' => "",
      ),
    ),
    'filepicker_stats' => array(
      'variables' => array(
        'header' => array(),
        'rows' => array(),
        'pref' => "",
        'suff' => "",
        'label' => "",
      ),
    ),
    'filepicker_fullpage' => array(
      'variables' => array(
        'file' => array(),
        'source' => "",
        'link' => 1,
      ),
    ),
    'filepicker_quota_message' => array(
      'variables' => array(
        'message1' => "",
        'message2' => "",
        'form' => NULL,
        'label' => "",
        'help' => "",
      ),
    ),
    'filepicker_fview' => array(
      'variables' => array(
        'file' => array(),
        'filepath' => "",
        'info' => array(),
      ),
    ),
    'filepicker_file_edit_header' => array(
      'variables' => array(
        'file' => array(),
        'source' => "",
      ),
    ),
    'filepicker_quota' => array(
      'variables' => array(
        'form' => NULL,
        'message' => "",
        'label' => "",
      ),
    ),
    'filepicker_user_config' => array(
      'variables' => array(
        'form' => NULL,
        'label' => "",
        'help' => "",
        'message1' => "",
        'message2' => "",
      ),
    ),
    'filepicker_userview' => array(
      'variables' => array(
        'view' => "",
        'form1' => NULL,
        'form2' => NULL,
        'form3' => NULL,
      ),
    ),
    'filepicker_adminview' => array(
      'variables' => array(
        'view' => "",
        'form1' => NULL,
        'form2' => NULL,
        'form3' => NULL,
      ),
    ),
    'filepicker_insert' => array(
      'variables' => array(
        'file' => NULL,
        'public' => NULL,
        'form1' => NULL,
        'form2' => NULL,
      ),
    ),
    'filepicker_upload_form' => array(
      'render element' => 'form'
    ),
    'filepicker_user_file_form' => array(
      'render element' => 'form'
    ),
    'filepicker_user_config_admin_form' => array(
      'render element' => 'form'
    ),
    'filepicker_admin_file_form' => array(
      'render element' => 'form'
    ),
    'filepicker_user_search_form' => array(
      'render element' => 'form'
    ),
    'filepicker_group_search_form' => array(
      'render element' => 'form'
    ),
    'filepicker_quota_form' => array(
      'render element' => 'form'
    ),
    'filepicker_edit_form' => array(
      'render element' => 'form'
    ),
    'filepicker_groups_form' => array(
      'render element' => 'form'
    ),
    'filepicker_group_delete_form' => array(
      'render element' => 'form'
    ),
    'filepicker_file_form' => array(
      'render element' => 'form'
    ),
    'filepicker_list_groups_form' => array(
      'render element' => 'form'
    ),
    'filepicker_list_public_groups_form' => array(
      'render element' => 'form'
    ),
    'filepicker_group_files_form' => array(
      'render element' => 'form'
    ),
    'filepicker_list_public_form' => array(
      'render element' => 'form'
    ),
    'filepicker_list_search_form' => array(
      'render element' => 'form'
    ),
    'filepicker_settings_form' => array(
      'render element' => 'form'
    ),
    'filepicker_list_admin_form' => array(
      'render element' => 'form'
    ),
    'filepicker_list_admin' => array(
      'variables' => array(
        'forms' => '',
        'message' => '',
        'pref' => '',
        'suff' => '',
        'label' => '',
      ),
    ),
    'filepicker_multitask_delete_form' => array(
      'render element' => 'form'
    ),
    'filepicker_multitask_groups_form' => array(
      'render element' => 'form'
    ),
    'filepicker_import_form' => array(
      'render element' => 'form'
    ),
    'filepicker_import_dir_form' => array(
      'render element' => 'form'
    ),
    'filepicker_admin_orphans_form' => array(
      'render element' => 'form',
    ),

  );
}

// preprocess for filepicker.tpl.php
function template_preprocess_filepicker(&$variables) {
  global $language;
  if (module_exists('admin_menu')) {
    admin_menu_suppress();
  }
  $variables['head_title']  = (drupal_get_title() ? strip_tags(drupal_get_title()) : variable_get('site_name', 'Drupal'));
  $variables['styles'] = drupal_get_css();
  $variables['scripts'] = drupal_get_js();
  $tabs = menu_local_tabs();
  $variables['tabs'] = theme('menu_local_tasks', array('primary' => $tabs['#primary']));
  $variables['messages'] = filepicker_strip_messages(theme('status_messages'));
  $variables['language'] = $language;
}

// set up the iframe
function theme_filepicker_iframe($variables) {
  $content = $variables['content'];
  $file = (isset($variables['file']) ? $variables['file'] : '');
  $public = (isset($variables['public']) ? $variables['public'] : FALSE);

  drupal_add_css(FILEPICKER_PATH . '/filepicker.css');
  if ($file) {
    global $user;
    $settings = array(
      'filepicker_iframe' => array(
        'isFCKeditor' => (module_exists('fckeditor') ? 'yes' : 'no' ),
        'isWysiwyg' => (module_exists('wysiwyg') ? 'yes' : 'no' ),
        'colorbox_enable' => (module_exists('colorbox') && filepicker_variable_get('filepicker_colorbox_enable', 0)),
        'colorbox_iframe' => (filepicker_get_colorbox_perms()),
        'file_new_window' => filepicker_variable_get('filepicker_use_new_window', 0),
        'node_editbody' => 'edit-body-' . filepicker_variable_get('filepicker_node_lang', '') . '-' . filepicker_variable_get('filepicker_node_pos', 0) . '-value',
      ),
    );
    drupal_add_js($settings, 'setting');
    drupal_add_js(FILEPICKER_PATH . '/filepicker_iframe.js');
  }
  return $content;
}

function theme_filepicker_list($variables) {
  $header = $variables['header'];
  $rows =  $variables['rows'];
  $max = $variables['max'];
  $message = $variables['message'];
  $pref = $variables['pref'];
  $suff = $variables['suff'];
  $label = $variables['label'];

  $output = ($label ? '<fieldset><legend>' . $label . '</legend>' : '');
  $build['filepicker_list'] = array(
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => $rows,
    '#empty' => $message,
  );
  $build['filepicker_pager'] = array('#theme' => 'pager');
  $output .= $pref . render($build) . $suff;
  $output .= ($label ? '</fieldset>' : '');
  return $output;

}

function theme_filepicker_stats($variables) {
  $header = $variables['header'];
  $rows =  $variables['rows'];
  $message = $variables['message'];
  $pref = $variables['pref'];
  $suff = $variables['suff'];
  $label = $variables['label'];

  $output = ($label ? '<fieldset><legend>' . $label . '</legend>' : '');
  if (count($rows)) {
    $output .= $pref . theme('table', array('header' => $header, 'rows' => $rows)) . $suff;
  }
  else {
    $output .= '<div class="messages">' . $message . '</div>';
  }
  $output .= ($label ? '</fieldset>' : '');
  return $output;
}

function theme_filepicker_quota_message($variables) {
  $message1 = $variables['message1'];
  $message2 = $variables['message2'];
  $form = $variables['form'];
  $label = $variables['label'];
  $help = $variables['help'];

  $output = ($label ? '<fieldset><legend>' . $label . '</legend>' : '');
  $output .= ($message1 ? '<div class="messages">' . $message1 . '</div>' : '') ;
  $output .= ($help ? '<div class="filep_help">' . $help . '</div>' : '');
  $output .= $form;
  $output .= ($message2 ? '<div class="messages">' . $message2 . '</div>' : '') ;
  $output .= ($label ? '</fieldset>' : '');
  return $output;
}

function theme_filepicker_fview($variables) {
  $file = $variables['file'];
  $filepath = $variables['filepath'];
  $info = $variables['info'];
  $output = '<div id="filep_file_view">';
  $output .= '<div id="filep_file_view_name">' . t('Name') . ": " . $file->file_name . '</div>';
  $output .= ($file->file_title ? '<div id="filep_file_view_title">' . t('Title') . ": " . $file->file_title . '</div>' : '');
  $output .= '<div id="filep_file_view_info">' . t('Size') . ": " . _filepicker_bkmg($info['file_size']) . '</div>';
  $output .= '</div>';
  return $output;
}

function theme_filepicker_file_edit_header($variables) {
  $file = $variables['file'];
  $source = $variables['source'];
  $output = '<div class="filep_help">' . t('Edit details for %f', array('%f' => $file->file_name )) . '</div>';
  return $output;
}

function theme_filepicker_quota($variables) {
  $form = $variables['quotaform'];
  $message = $variables['message'];
  $label = $variables['label'];
  $output = ($label ? '<fieldset><legend>' . $label . '</legend>' : '');
  $output .= ($message ? '<div class="messages">' . $message . '</div>' : '') ;
  $output .= $form;
  $output .= ($label ? '</fieldset>' : '');
  return $output;
}

function theme_filepicker_user_config($variables) {
  $form = $variables['form'];
  $label = $variables['label'];
  $help = $variables['help'];
  $message1 = $variables['message1'];
  $message2 = $variables['message2'];
  $output = ($label ? '<fieldset><legend>' . $label . '</legend>' : '');
  $output .= ($help ? '<div class="filep_help">' . $help . '</div>' : '');
  $output .= ($message1 ? '<div class="messages">' . $message1 . '</div>' : '') ;
  $output .= $form;
  $output .= ($message2 ? '<div class="messages">' . $message2 . '</div>' : '') ;
  $output .= ($label ? '</fieldset>' : '');
  return $output;
}

function theme_filepicker_userview($variables) {
  $view = $variables['view'];
  $form1 = $variables['form1'];
  $form2 = $variables['form2'];
  $form3 = $variables['form3'];

  $output = "";
  $output .= $view;
  $output .= '<br />';
  $output .= $form1;
  $output .= '<br />';
  $output .= $form2;
  $output .= $form3;
  return $output;
}

function theme_filepicker_adminview($variables) {
  $view = $variables['view'];
  $form1 = $variables['form1'];
  $form2 = $variables['form2'];
  $form3 = $variables['form3'];

  $output = "";
  $output .= $view;
  $output .= '<br />';
  $output .= $form1;
  $output .= '<br />';
  $output .= $form2;
  $output .= $form3;
  return $output;
}

function theme_filepicker_insert($variables) {
  $file = $variables['file'];
  $public = $variables['public'];
  $form1 = $variables['form1'];
  $form2 = $variables['form2'];
  $output = "";
  if ($file) {
    $filepath = filepicker_get_file_path($file, ($public ? $file->uid : FALSE ));
    $output .= '<div class="filep_help">' . t('Choose the settings you want, place the cursor in the Body box above and Insert file.') . '</div>';
    $output .= '<div id="filep_file_view_name">' . t('Name') . ": " . $file->file_name . '</div>';
    $output .= ($file->file_title ? '<div id="filep_file_view_title">' . t('Title') . ": " . $file->file_title . '</div>' : '');
    $output .= $form1;
    $output .= $form2;
  }
  return $output;
}

function theme_filepicker_upload_form($variables) {
  $form = $variables['form'];
  $output = '';
  $max_uploads = filepicker_variable_get('filepicker_max_uploads', 1);
  $max_filesize = ini_get('upload_max_filesize');

  $form['maxmsg']['#markup'] = '<div class="messages">' . t('Browse your computer for up to !c, Max %max Total', array('!c' => format_plural($max_uploads, '1 File', '@count Files'), '%max' => $max_filesize) ) . '</div>';
  for ($ct = 1; $ct <= $max_uploads; $ct++) {
    $form['file_upload_' . $ct]['#prefix'] = "<div id='filepicker_upload_link_wrapper_$ct'>";
    $form['title_' . $ct]['#suffix'] = '</div>';
    if (isset($form['link_' . $ct])) {
      $form['link_' . $ct]['#markup'] = "<div class='filepicker_upload_link' id='filepicker_upload_link_$ct' style='display:none'>" . l(t('Upload another'), '', array(
        'attributes' => array(
          'onClick' => "Drupal.filepicker_upload_link_click($ct); return false;"
        )
      )) . '</div>';
    }
  }
  $output .= drupal_render_children($form);
  return $output;
}

function theme_filepicker_user_file_form($variables) {
  $form = $variables['form'];
  $output = '';
  $output .= drupal_render_children($form);
  return $output;
}

function theme_filepicker_user_config_admin_form($variables) {
  $form = $variables['form'];
  $output = '';
  $form['submit']['#prefix'] = '<div class="container-inline">';
  $form['reset']['#suffix'] = '</div>';
  $output .= drupal_render_children($form);
  return $output;
}

function theme_filepicker_admin_file_form($variables) {
  $form = $variables['form'];
  $output = '';
  $output .= drupal_render_children($form);
  return $output;
}

function theme_filepicker_user_search_form($variables) {
  $form = $variables['form'];
  $output = '';
  $form['filepicker_currentuser']['#prefix'] = '<div id="filep_users_form" class="container-inline">';
  $form['filepicker_user_search_submit']['#suffix'] = '</div>';
  $output .= drupal_render_children($form);
  return $output;
}

function theme_filepicker_group_search_form($variables) {
  $form = $variables['form'];
  $output = '';
  $form['filepicker_currentgroup']['#prefix'] = '<div id="filep_groups_form" class="container-inline">';
  $form['filepicker_group_search_submit']['#suffix'] = '</div>';
  $output .= drupal_render_children($form);
  return $output;
}

function theme_filepicker_quota_form($variables) {
  $form = $variables['form'];
  $output = '';
  $form['filepicker_quota']['#prefix'] = '<div id="filep_quota_form" class="container-inline">';
  $form['submit']['#suffix'] = '</div>';
  $output .= drupal_render_children($form);
  return $output;
}

function theme_filepicker_edit_form($variables) {
  $form = $variables['form'];
  $output = '';
  $form['submit']['#prefix'] = '<div id="filep_controls">';
  $form['cancel']['#suffix'] = '</div>';
  $output .= drupal_render_children($form);
  return $output;
}

function theme_filepicker_groups_form($variables) {
  $form = $variables['form'];
  $output = '';
  $output .= drupal_render_children($form);
  return $output;
}

function theme_filepicker_group_delete_form($variables) {
  $form = $variables['form'];
  $output = '';
  $output .= drupal_render_children($form);
  return $output;
}

function theme_filepicker_file_form($variables) {
  $form = $variables['form'];
  $output = '';
  if (isset($form['delete'])) {
    $form['insert']['#prefix'] = '<div id="filep_controls">';
    $form['delete']['#suffix'] = '</div>';
  }
  $output .= drupal_render_children($form);
  return $output;
}

function theme_filepicker_list_groups_form($variables) {
  $form = $variables['form'];
  $output = '';
  $form['gid']['#prefix'] = '<div id="filep_groups_form" class="container-inline">';
  $form['submit']['#suffix'] = '</div>';
  $output .= drupal_render_children($form);
  return $output;
}

function theme_filepicker_list_public_groups_form($variables) {
  $form = $variables['form'];
  $output = '';
  $form['gid']['#prefix'] = '<div id="filep_groups_form" class="container-inline">';
  $form['submit']['#suffix'] = '</div>';
  $output .= drupal_render_children($form);
  return $output;
}

function theme_filepicker_group_files_form($variables) {
  $form = $variables['form'];
  $output = '';
  $output .= drupal_render_children($form);
  return $output;
}

function theme_filepicker_list_public_form($variables) {
  $form = $variables['form'];
  $output = '';
  $form['filepicker_list_public']['#prefix'] = '<div id="filep_list_form" class="container-inline">';
  $form['submit']['#suffix'] = '</div>';
  $output .= drupal_render_children($form);
  return $output;
}

function theme_filepicker_list_search_form($variables) {
  $form = $variables['form'];
  $output = '';
  $form['filepicker_list_search']['#prefix'] = '<div id="filep_search_form" class="container-inline">';
  $form['reset']['#suffix'] = '</div>';
  $output .= drupal_render_children($form);
  return $output;
}

function theme_filepicker_settings_form($variables) {
  $form = $variables['form'];
  $output = '';

  $jshide = ($form['filepicker_import']['filepicker_import_enabled']['#default_value'] ? '' : ' class="js-hide"');
  $form['filepicker_import']['filepicker_import_delete']['#prefix'] = '<div id="wrap-filepicker-import"' . $jshide . '>';
  $form['filepicker_import']['filepicker_import_max']['#suffix'] = '</div>';

  $jshide = ($form['filepicker_groups']['filepicker_groups_enabled']['#default_value'] ? '' : ' class="js-hide"');
  $form['filepicker_groups']['filepicker_public_enabled']['#prefix'] = '<div id="wrap-filepicker-groups"' . $jshide . '>';
  $form['filepicker_groups']['filepicker_groups_in_upload_enabled']['#suffix'] = '</div>';

  $jshide = ($form['filepicker_progress']['filepicker_upload_progress_enabled']['#default_value'] ? '' : ' class="js-hide"');
  $form['filepicker_progress']['filepicker_upload_progress_delay']['#prefix'] = '<div id="wrap-filepicker-upload-progress"' . $jshide . '>';
  if (version_compare(phpversion(), FILEPICKER_UPLOAD_STATUS_MIN_PHP) >= 0 && extension_loaded('uploadprogress')) {
    $form['filepicker_progress']['filepicker_uploadprogress']['#suffix'] = '</div>';
  }
  else {
    $form['filepicker_progress']['filepicker_upload_progress_message']['#suffix'] = '</div>';
  }

  $jshide = ($form['filepicker_quotas']['filepicker_quota_byrole']['#default_value'] ? '' : ' class="js-hide"');
  $form['filepicker_quotas']['filepicker_quota_role']['#prefix'] = '<div id="wrap-filepicker-quota-role"' . $jshide . '>';
  $form['filepicker_quotas']['filepicker_quota_role']['#suffix'] = '</div>';
  if (isset($form['filepicker_settings']['filepicker_admin_message'])) {
    $form['filepicker_settings']['filepicker_admin_message']['#prefix'] = '<div class="messages">';
    $form['filepicker_settings']['filepicker_admin_message']['#suffix'] = '</div>';
  }

  $output .= drupal_render_children($form);
  return $output;
}

function theme_filepicker_list_admin_form($variables) {
  $form = $variables['form'];
  $output = '';
  $public = $form['options']['public']['#value'];
  if ($public) {
    $rows = $form['files']['#options'];
    $header = $form['files']['#header'];
    $output .= theme('table', array('header' => $header, 'rows' => $rows));
    $output .= theme('pager');
  }
  else {
    $form['options']['#prefix'] = '<div class="container-inline">';
    $form['options']['#suffix'] = '</div>';
    $output .= drupal_render_children($form);
  }
  return $output;
}

function theme_filepicker_list_admin($variables) {
  $forms = $variables['forms'];
  $pref = $variables['pref'];
  $suff = $variables['suff'];
  $label = $variables['label'];
  $output = ($label ? '<fieldset><legend>' . $label . '</legend>' : '');
  $output .= $pref;
  $output .= $forms['list_search'];
  $output .= $forms['list_groups'];
  $output .= $forms['list_public'];
  $output .= $forms['list_public_groups'];
  $output .= $forms['list_admin'];
  $output .= $suff;
  $output .= ($label ? '</fieldset>' : '');
  return $output;
}

function theme_filepicker_multitask_delete_form($variables) {
  $form = $variables['form'];
  $output = '';
  $count = $form['countnids']['#value'];
  $output .= '<p>' . t('You have selected %c to be deleted', array('%c' => format_plural( $count, '1 file', '@count files'))) . '</p>';
  $output .= drupal_render_children($form);
  return $output;
}

function theme_filepicker_multitask_groups_form($variables) {
  $form = $variables['form'];
  $output = '';
  $count = $form['countnids']['#value'];
  $output .= '<p>' . t('You have selected %c to be grouped', array('%c' => format_plural( $count, '1 file', '@count files'))) . '</p>';
  $output .= drupal_render_children($form);
  return $output;
}

function theme_filepicker_import_form($variables) {
  $form = $variables['form'];
  $output = '';
  $markup = $form['total']['#markup'];
  $form['total']['#markup'] = '<p>' . $markup . '</p>';
  $output .= drupal_render_children($form);
  return $output;
}

function theme_filepicker_import_dir_form($variables) {
  $form = $variables['form'];
  $output = '';
  $output .= drupal_render_children($form);
  return $output;
}

function theme_filepicker_admin_orphans_form($variables) {

  $form = $variables['form'];
  $output = '';
  $form['msg']['#prefix'] = '<div class="messages">';
  $form['msg']['#suffix'] = '</div>';
  $output .= drupal_render_children($form);
  return $output;
}
